### ISSUE TITLE
Va bien tu practica Monica te sugiero algunas Mejoras

### ISSUE THREAD

**Issue by sidlors** [JavaUAM2016/PracticasOCA#10]
Hola @monilezama 

Va bien tu practica, casi terminas

solo que te quiero hacer una observación en tus clases control que estan en el paquete:

https://github.com/JavaUAM2016/PracticasOCA/tree/master/Practica3/monilezama/JavaApp/src/mx/edu/uam/practica3/controles

En cada control has agregado una atributo a la clase que si lo piensas bien son atributos del electrodomestico y no del control, ¿¿por que te lo digo??

Si ese atributo queda a nivel de control, el control queda limitado a por ejemplo max vol, y eso es un atributo de cada televisor, lo que nos lleva a un desacoplamiento de nuestras clases modelo y de sus controladores, que opinas???

Por ultimo Agrega el resto de los electrodomesticos por favor

si tienes una duda usa este medio, o bien en el Room

https://gitter.im/sidlors/JavaUAM2016_ROOM

Saludos!!

**Comment by monilezama** [comment]
Cuantos electrodomesticos deben ser?

**Comment by sidlors** [comment]
Hola Monica, buen dia

3 electrodomésticos al menos, la unica condición es que tengan su control remoto; pruébalos en el main

Saludos

**Comment by monilezama** [comment]
cambie lo del volumen maximo, y agregue la clase de dvd y su control.
podrias checar si se subio correctamente?esa parte aun no me queda
completamente clara gracias :D

**Comment by sidlors** [comment]
es correcto monica, te quedo muy bien la practica, 

excelente!    "issue" cerrado 👍
